DELETE FROM S_AUTH WHERE AUTH_ID='S_DEPT_LIST';
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_DEPT_LIST' AUTH_ID,'部门' NAME, 'SYS' PARENT_ID, '/sys/Dept/list.do' PARAM, '1' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);

DELETE FROM S_AUTH WHERE AUTH_ID='S_DEPT_ADD';
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_DEPT_ADD' AUTH_ID,'部门增加' NAME, 'S_DEPT_LIST' PARENT_ID, '' PARAM, '' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);

DELETE FROM S_AUTH WHERE AUTH_ID='S_DEPT_EDIT';
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_DEPT_EDIT' AUTH_ID,'部门修改' NAME, 'S_DEPT_LIST' PARENT_ID, '' PARAM, '' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);

DELETE FROM S_AUTH WHERE AUTH_ID='S_DEPT_DEL';
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_DEPT_DEL' AUTH_ID,'部门删除' NAME, 'S_DEPT_LIST' PARENT_ID, '' PARAM, '' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);

