DELETE FROM S_AUTH WHERE AUTH_ID='S_GROUP_LIST';
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_GROUP_LIST' AUTH_ID,'用户组' NAME, 'SYS' PARENT_ID, '/sys/Group/list.do' PARAM, '1' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);

DELETE FROM S_AUTH WHERE AUTH_ID='S_GROUP_ADD';
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_GROUP_ADD' AUTH_ID,'用户组增加' NAME, 'S_GROUP_LIST' PARENT_ID, '' PARAM, '' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);

DELETE FROM S_AUTH WHERE AUTH_ID='S_GROUP_EDIT';
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_GROUP_EDIT' AUTH_ID,'用户组修改' NAME, 'S_GROUP_LIST' PARENT_ID, '' PARAM, '' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);

DELETE FROM S_AUTH WHERE AUTH_ID='S_GROUP_DEL';
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_GROUP_DEL' AUTH_ID,'用户组删除' NAME, 'S_GROUP_LIST' PARENT_ID, '' PARAM, '' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);

INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_GROUP_ASSIGN_USER' AUTH_ID,'分配用户' NAME, 'S_GROUP_LIST' PARENT_ID, '' PARAM, '' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);
