DELETE FROM S_AUTH WHERE AUTH_ID='S_ROLE_LIST';
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_ROLE_LIST' AUTH_ID,'角色' NAME, 'SYS' PARENT_ID, '/sys/Role/list.do' PARAM, '1' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);

DELETE FROM S_AUTH WHERE AUTH_ID='S_ROLE_ADD';
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_ROLE_ADD' AUTH_ID,'角色增加' NAME, 'S_ROLE_LIST' PARENT_ID, '' PARAM, '' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);

DELETE FROM S_AUTH WHERE AUTH_ID='S_ROLE_EDIT';
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_ROLE_EDIT' AUTH_ID,'角色修改' NAME, 'S_ROLE_LIST' PARENT_ID, '' PARAM, '' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);

DELETE FROM S_AUTH WHERE AUTH_ID='S_ROLE_DEL';
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_ROLE_DEL' AUTH_ID,'角色删除' NAME, 'S_ROLE_LIST' PARENT_ID, '' PARAM, '' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);

INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_ROLE_ASSIGN_AUTH' AUTH_ID,'角色分配权限' NAME, 'S_ROLE_LIST' PARENT_ID, '' PARAM, '' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);
INSERT INTO S_AUTH (AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT) SELECT AUTH_ID,NAME,PARENT_ID,PARAM,MENU,SORT FROM (select 'S_ROLE_ASSIGN_ROLE' AUTH_ID,'分配角色' NAME, 'S_USER_LIST' PARENT_ID, '' PARAM, '' MENU, '' SORT FROM dual) a where NOT EXISTS (select 1 from S_AUTH b where a.auth_id = b.auth_id);
